**Benefits of Numpy on Python List**

1. Less Memory
2. Fast
3. Convinient

In [10]:
import numpy as np
import sys
import time

**Python List taking more memory compared to Numpy**

In [6]:
l = range(1000)
print("size of python list", sys.getsizeof(5)*len(l))

array = np.arange(1000)
print("size of numpy array", array.size*array.itemsize)

size of python list 28000
size of numpy array 4000


**Python List is slow than numpy**

In [13]:
ranges = 10000000
lst1 = range(ranges)
lst2 = range(ranges)

n1 = np.arange(ranges)
n2 = np.arange(ranges)


start = time.time()
lst_result = [(x+y) for x,y in zip(lst1,lst2)]
print("python list took",(time.time()-start)*1000)

start = time.time()
num_res = n1 + n2
print("numpy took", (time.time()-start)*1000)

python list took 1320.4221725463867
numpy took 11.672496795654297


**Iterate numpy array using nditer**

In [15]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
for x in np.nditer(a, order = 'C'):
    print(x)

0
1
2
3
4
5
6
7
8


In [20]:
for x in np.nditer(a, order = 'F',flags = ['external_loop']):
    print(x)

[0 3 6]
[1 4 7]
[2 5 8]


**Evenly spaced values**

In [23]:
a = np.linspace(10,30,6)
print(a)

[10. 14. 18. 22. 26. 30.]
